### ISSUE TITLE
midi cutting off sound

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#170] opened 2024-12-25 13:56 UTC
hello ivonasek could you fix MidiSynch so that it doesn't cut off the sound and there is no undertone

**Comment by lvonasek** [comment] 2024-12-25 15:08
Please stop creating duplicates of one bug or we will have to ban you.

Duplicate of https://github.com/longjunyu2/winlator/issues/68

**Closed by lvonasek** 2024-12-25 15:08 UTC
Labels: bug, duplicate
