### ISSUE TITLE
[BUG] MIDI: Strange cut-off tones and noise that shouldn't be there.

### ISSUE THREAD

**Issue by TheBoxGame** [longjunyu2/winlator#115] opened 2024-09-15 15:34 UTC
Strange cut-off tones and noise that shouldn't be there when playing music in the game Use Soundfront Microsoft GS Wavetable Synth 

here is a recording of using midi in winelator

https://github.com/user-attachments/assets/8d35a068-eb64-4878-8db8-dacc0e5d6ca2

and here from the net how it should play and with other soundfronts

https://github.com/user-attachments/assets/7cca8eed-0526-4c4e-a6c3-b107a8c164f8

will this be fixed in the next commit
![Screenshot_2024-09-15-17-34-18-128_com winlator](https://github.com/user-attachments/assets/56f0e81f-3d1d-47a7-a67f-efbcefe3a0bd)

I'm giving you a screenshot of the soundfront that I used in winelator

**Comment by longjunyu2** [comment] 2024-09-15 15:47
This issue seems to be a duplicate of #68. Thanks for your feedback, I will have a look.

**Comment by TheBoxGame** [comment] 2024-09-20 14:35
@longjunyu2 you will fix it

**Comment by longjunyu2** [comment] 2024-09-20 14:47
@TheBoxGame will you fix it?

**Comment by TheBoxGame** [comment] 2024-09-20 14:52
@longjunyu2 ok I wanted to ask if this will be fixed in version 7.1.4

**Comment by TheBoxGame** [comment] 2024-09-20 14:53
Iwonasek is also a programmer ?

**Comment by longjunyu2** [comment] 2024-09-20 15:00
@TheBoxGame I hope this will be fixed in next version. Fix MIDI = Take half of day, Time is always not enough for me :(
If you don't want to wait, its better to find another person who is more **professional** and have more free time :(

**Comment by longjunyu2** [comment] 2024-09-20 15:01
@TheBoxGame We are all busy these days, don't ping please..

**Comment by TheBoxGame** [comment] 2024-09-20 15:09
> @TheBoxGameMam nadzieję, że to zostanie naprawione w następnej wersji. Napraw MIDI = Zajmuje pół dnia, Czasu mi zawsze brakuje :( Jeśli nie chcesz czekać, lepiej znajdź innych, którzy są bardziej profesjonalni i mają więcej wolnego czasu :(

Ok Sorry

**Comment by lvonasek** [comment] 2024-12-25 15:07
Duplicate of https://github.com/longjunyu2/winlator/issues/68

**Closed by lvonasek** 2024-12-25 15:07 UTC
Labels: bug, duplicate, audio
