### ISSUE TITLE
[BUG] Xinput - old gamepad style missing

### ISSUE THREAD

**Issue by Luihart** [longjunyu2/winlator#89] opened 2024-09-02 16:00 UTC
**Device Information**
- Device Model: Redmi Note 12 Turbo/ Ayn Odin 2 Max
- Device Processor Model: SD7+Gen2/SD8Gen2
- Android Version: 13
- Kernel Version: 5.10.192

**Application Configuration Information**
- App Version: 7.1.3 (yours and in modded winlator also)
- Display Driver: Turnip-24.3.0 (not related anyway
- dxwrapper: DXVK 1.10.3 async
- box64 Version:  0.3.1/ 0.3.1 8g2
- box64 Preset: custom - Compatibility with fastnan and fastround 1

**Description of the Issue**
Games like Resident Evil Remake 2/3, Devil May Cry 5 and Splinter Cell Conviction/Blacklist needs the older Xinput standard gamepad style which were present in 7.1.1 and 7.1.2
Since switchable Xinput and Dinput, this Option is only available for dinput. Using dinput and using the old style doesnt fix the Problem either (gamepad not recognized at all for these games or no Reaction)

Update: changing xinput to old legacy style and switching back to xinput doesnt work too. Its still mapped as modern xinput style

**Steps to Reproduce**
Please describe the steps to reproduce the issue:
1. create game shortcut
2. change xinput style and virtual gamepad
3. run the game
4. repeated process with dinput style and modern xinput mode
5. repeated process with old style dinput mode

**Expected Behavior**
Working controls in x360 layout but due xinput modern style only buttons are mapped wrong

**Additional Information**
Worked fine in 7.1.1 and 7.1.2

**Comment by Dragon-11976** [comment] 2024-09-02 18:51
@Luihart The problem, my friend, is only in Dinput and not in Xinput because the new fix for Xinput fixed some strange problems in some games in which a controller works automatically and by itself. Also, the game Dragon's Dogma used to work with two controllers at the same time. In this update, this problem was solved. Also, in this new update, the game Sekiro was supported. The games that I mentioned have their own problem with Dinput and not Xinput 😁
![Screenshot_2024-09-02-01-04-20-761_ru zdevs zarchiver](https://github.com/user-attachments/assets/b62c6f1c-010b-4af4-8939-60d8081a1948)

**Comment by Dragon-11976** [comment] 2024-09-02 18:54
> @Luihart The problem, my friend, is only in Dinput and not in Xinput because the new fix for Xinput fixed some strange problems in some games in which a controller works automatically and by itself. Also, the game Dragon's Dogma used to work with two controllers at the same time. In this update, this problem was solved. Also, in this new update, the game Sekiro was supported. The games that I mentioned have their own problem with Dinput and not Xinput 😁 ![Screenshot_2024-09-02-01-04-20-761_ru zdevs zarchiver](https://private-user-images.githubusercontent.com/151464230/363774948-b62c6f1c-010b-4af4-8939-60d8081a1948.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMDM1MDUsIm5iZiI6MTcyNTMwMzIwNSwicGF0aCI6Ii8xNTE0NjQyMzAvMzYzNzc0OTQ4LWI2MmM2ZjFjLTAxMGItNGFmNC04OTM5LTYwZDgwODFhMTk0OC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMlQxODUzMjVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDQ2YzlhYTc0MjU1ZWZkNWE1MjVmZGQ3ZWFjOGQ3MGNmY2IzY2I5NjEzMTE3NGU0NWQ5MTU3NWMyMDE1ZGU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Lylf8KK0J4jW4uFRr4wp5FTRcMS135Of_Maw7FET3QU)

@djdp77 @brujo5 If the games were working for you in the last update 7.1.2 on xinput and in this one they no longer work what you have to do is enable xinput and Dinput together so that the games that were working previously in the last update will work for you. 
![Screenshot_2024-08-31-18-21-30-788_com winlator-edit](https://github.com/user-attachments/assets/6e107654-a590-40e6-a569-ad2fe554df08)
And if you want to unlock some games that were not supported in xinput control such as the game sekiro what you have to do is activate the xinput option alone only and this also fixes some control problems in some games such as Dragon's dogma 😁
![Screenshot_2024-08-31-18-21-20-854_com winlator-edit](https://github.com/user-attachments/assets/e4854382-f451-4ea2-8f38-1a80bedeae14)

**Comment by Dragon-11976** [comment] 2024-09-02 19:23
@longjunyu2 Thank you for this new update, frankly, all the problems that were in 7.1.2 have been fixed.

Also, the Dragon's dogma game has fixed the problem that I told you about. Thank you. Now the game works with xinput in an amazing way and all the buttons are working and there is no inverted button. The game now works with one controller for me, Xbox 360. Thank you, legend.
![Screenshot_2024-08-29-19-49-09-113_com winlator](https://github.com/user-attachments/assets/d8122732-c318-4d70-af92-d7276cfb233a)

Also, in this new update, finally, the game sekiro has been supported on xinput. I did not expect this. Thank you very much.
![Screenshot_2024-08-30-01-26-51-806_com winlator](https://github.com/user-attachments/assets/6dbabccc-777f-4e0e-8159-5fdb2cd21596)
Only in the game THYMESIA, it is not supported on xinput. When I try it on Dinput, only one button works, it is my analogue. Move in the game, but the camera and all the other buttons do not work at all. Another immersion. Thank you for this update. It has fixed many amazing things. See you later
![Screenshot_2024-08-30-03-59-06-207_com winlator](https://github.com/user-attachments/assets/5e43a550-488f-4b64-8f67-60513a2cf72c)
![Screenshot_2024-08-30-04-06-24-064_com winlator](https://github.com/user-attachments/assets/4075c388-0688-47c2-89a6-9889ea584d75)

**Comment by Dragon-11976** [comment] 2024-09-02 19:25
@lvonasek 
![Screenshot_2024-08-30-03-49-52-080_com winlator](https://github.com/user-attachments/assets/2dade401-2be5-4e25-883d-82edc8a4ded3)
![Screenshot_2024-08-30-03-53-01-103_com winlator](https://github.com/user-attachments/assets/80d7f50c-cda6-4e90-8040-3ba7e5db3070)
![Screenshot_2024-08-30-03-53-15-143_com winlator](https://github.com/user-attachments/assets/e2432420-d3b5-4bfe-a7d0-2fd3b013e26d)
![Screenshot_2024-08-30-03-53-24-004_com winlator](https://github.com/user-attachments/assets/9ed6406f-4911-4628-a204-6854c6c74140)
![Screenshot_2024-08-30-19-59-39-854_com miui gallery-edit](https://github.com/user-attachments/assets/8e62297f-22c7-4574-8946-b0399559133b)

1. There is also a problem with the Greed Fall game, where when I run the game in performance mode, a message appears that says “error” for my memory. This message appears in the original version 7.1. Also, this problem only appears in performance mode. As for Compatibility mode, the game works well without any message appearing at all. I tried everything with this problem and all methods did not work. The game is not supported in performance mode, unfortunately. I hope that this problem will be fixed in future updates. Thank you for this wonderful update 🫡

**Comment by lvonasek** [comment] 2024-09-02 20:00
@Dragon-11976 please try to avoid pinging the developers. We are all busy and filling our mailboxes with messages make the progress only slower.

The issue in the last message seems to be related to the wine or other component version. If that's the case then we cannot do much except waiting on a new version.

What you can try is to set "Video Memory Size" in the container settings to 4096MB (for that you need device with at least 6GB RAM).

**Comment by Dragon-11976** [comment] 2024-09-02 20:53
> @Dragon-11976يرجى محاولة تجنب إرسال رسائل إلى المطورين. فنحن جميعًا مشغولون وملء صناديق البريد الخاصة بنا بالرسائل يجعل التقدم أبطأ.
> 
> يبدو أن المشكلة في الرسالة الأخيرة تتعلق بإصدار النبيذ أو إصدار مكون آخر. إذا كانت هذه هي الحالة، فلن نتمكن من فعل الكثير سوى انتظار إصدار جديد.
> 
> ما يمكنك تجربته هو تعيين "حجم ذاكرة الفيديو" في إعدادات الحاوية إلى 4096 ميجابايت (ولهذا تحتاج إلى جهاز يحتوي على ذاكرة وصول عشوائي (RAM) بسعة 6 جيجابايت على الأقل).

Sorry only this game and some games suffer from this problem especially in performance mode I tried everything with it and it did not work This game has a problem with performance mode I just sent this to see if there is a solution for it or not because it works without problems in Compatibility mode because this problem exists in all versions of winlator especially when I want to run the game in performance mode it seems that it has a problem with DYNAREC Sorry again 😅

**Comment by lvonasek** [comment] 2024-09-03 04:52
It seems this is a problem directly in the game itself as it crashes even on Windows: https://steamcommunity.com/app/606880/discussions/1/2552901289724636487/

**Comment by longjunyu2** [comment] 2024-09-03 13:22
Sorry, I don't understand what is old gamepad style for xinput. I think what you mean is old gamepad style for dinput.

**Comment by longjunyu2** [comment] 2024-09-07 15:43
Ayn Odin2 Max, when `Enabld XInput` is checked, the gamepad works properly in Resident Evil 2 Remake. The test result from another person is the same, and I am unable to reproduce your issue.

**Closed by longjunyu2** 2024-09-07 15:43 UTC
Labels: invalid, input
